ProductWeb/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ProductWeb.Data;
using ProductWeb.Services;
using ProductWeb.Services.IService;
using ProductWeb.ViewModels;
using System.Security.Claims;

namespace ProductWeb.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ProductContext _productContext;
        private readonly ShoppingCartService _shoppingCartService;
		private readonly IWebHostEnvironment _webHostEnvironment;

		[BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }

        public CartController(ProductContext productContext, ShoppingCartService shoppingCartService,
            IWebHostEnvironment webHostEnvironment)
        {
            _productContext = productContext;
            _shoppingCartService = shoppingCartService;
			_webHostEnvironment = webHostEnvironment;
		}
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new()
            {
                ListCart = _productContext.ShoppingCarts.Include(p => p.Product)
                .Where(p => p.UserId == userId).ToList(),
                OrderHeader = new()
            };

            if(ShoppingCartVM.ListCart.Count() == 0) 
            {
                TempData["message"] = "คุณยังไม่ได้เลือกสินค้า";
                return RedirectToAction("Index","Home");
            }

            foreach (var item in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += item.Product.Price * item.Count;
            }

            return View(ShoppingCartVM);
        }

        public IActionResult Plus(int cartId)
        {
            var cart = _productContext.ShoppingCarts.Find(cartId);
            _shoppingCartService.IncrementCount(cart, 1);
            _shoppingCartService.Save();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Minus(int cartId)
        {
            var cart = _productContext.ShoppingCarts.Find(cartId);

            if (cart.Count > 1)
            {
                _shoppingCartService.DecrementCount(cart, 1);
                _shoppingCartService.Save();
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int cartId)
        {
            var cart = _productContext.ShoppingCarts.Find(cartId);
            _productContext.Remove(cart);
            _productContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Summary()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = _productContext.ShoppingCarts.Include(x => x.Product).Where(u => u.UserId.Equals(userId)),
                OrderHeader = new()
            };

            ShoppingCartVM.OrderHeader.User = _productContext.Users.Find(userId);

            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.User.FullName;
            ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.User.StreetAddress;
            ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.User.City;
            ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.User.State;
            ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.User.PostalCode;

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Product.Price * cart.Count);
            }
            return View(ShoppingCartVM);

        }

        //[HttpPost]
        public IActionResult SummaryPost()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

			ShoppingCartVM.ListCart = _productContext.ShoppingCarts.Include(x => x.Product)
                .Where(u => u.UserId.Equals(userId));

			ShoppingCartVM.OrderHeader.UserId = userId;
			ShoppingCartVM.OrderHeader.PaymentDate = DateTime.Now;
			ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusPending;

			#region Image Management
			string wwwRootPath = _webHostEnvironment.WebRootPath;
            var file = ShoppingCartVM.file;

			if (file != null)
			{
				string fileName = Guid.NewGuid().ToString();
				var extension = Path.GetExtension(file.FileName);
				var uploads = wwwRootPath + SD.PaymentPath;

				if (!Directory.Exists(uploads)) Directory.CreateDirectory(uploads);

				//บันทึกรุปภาพใหม่
				using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
				{
					file.CopyTo(fileStreams);
				}
				ShoppingCartVM.OrderHeader.PaymentImage = fileName + extension;
			}
			#endregion

			_productContext.OrderHeaders.Add(ShoppingCartVM.OrderHeader); //One
			_productContext.SaveChanges();

			foreach (var cart in ShoppingCartVM.ListCart) //Many
			{
				OrderDetail orderDetail = new()
				{
					ProductId = cart.ProductId,
					OrderId = ShoppingCartVM.OrderHeader.Id,
					Count = cart.Count
				};
				_productContext.OrderDetails.Add(orderDetail);
			}

			_productContext.ShoppingCarts.RemoveRange(ShoppingCartVM.ListCart); //ลบตะกร้า
			_productContext.SaveChanges();

			TempData["message"] = "successful transaction";
			return RedirectToAction("Index", "Home");
		}


	}
}

ProductWeb/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ProductContext _productContext;

        public CategoryController(ProductContext productContext)
        {
            _productContext = productContext;
        }
        public IActionResult Index()
        {
            var result = _productContext.Categories.ToList();
            return View(result);
        }

        public IActionResult UpCreate(int? id) 
        {
            var category = new Category();

            if (id == null || id == 0)
            {
                //create
            }
            else
            {
                //update
                category = _productContext.Categories.Find(id);
                if(category == null) 
                {
                    TempData["message"] = "ไม่พบข้อมูล";
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(category);
        }

        [HttpPost]
        public IActionResult UpCreate(Category category)
        {
            var id = category.Id;

            if (id == 0)
            {
                //create
                _productContext.Categories.Add(category);
            }
            else
            {
                //update
                _productContext.Update(category);
            }

            _productContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int id) 
        {
            var category = _productContext.Categories.Find(id);

            if (category != null)
            {
                var product=_productContext.Products.Where(p => p.CategoryId == id).FirstOrDefault();
                if (product != null) 
                {
                    TempData["message"] = "ไม่สามารถลบได้ มีการใช้งานอยู่";
                    return RedirectToAction(nameof(Index));
                }

                _productContext.Categories.Remove(category);
                _productContext.SaveChanges();
                TempData["message"] = "ลบสำเร็จเรียบร้อย";
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

ProductWeb/Controllers/ProductController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProductWeb.ViewModels;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace ProductWeb.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductContext _productContext;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(ProductContext productContext, IWebHostEnvironment webHostEnvironment)
        {
            _productContext = productContext;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var products = _productContext.Products.Include(p => p.Category).ToList();

            foreach (var item in products)
            {
                if (!string.IsNullOrEmpty(item.ImageUrl))
                {
                    item.ImageUrl = SD.ProductPath + "\\" + item.ImageUrl;
                }
            }
            return View(products);
        }

        public IActionResult UpCreate(int? id)
        {
            var productVM = new ProductVM()
            {
                Product = new()
                {
                    Name = "test",
                    Description = "test",
                    Price = 1,
                },
                CategoryList = _productContext.Categories.Select(item => new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString(),
                })
            };

            if (id != null && id != 0)
            {
                //update
                productVM.Product = _productContext.Products.Find(id);

                if (productVM.Product == null)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(productVM);
        }

        [HttpPost]
        public IActionResult UpCreate(ProductVM productVM)
        {
            if (!ModelState.IsValid) return View(productVM);

            #region การจัดรูปภาพ
            string wwwRootPath = _webHostEnvironment.WebRootPath;
            var file = productVM.file;

            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var extension = Path.GetExtension(file.FileName);
                var uploads = wwwRootPath + SD.ProductPath; // wwwroot\images\product

                if (!Directory.Exists(uploads)) Directory.CreateDirectory(uploads);


                //กรณีมีรูปภาพเดิมต้องลบทิ้งก่อน
                if (!string.IsNullOrEmpty(productVM.Product.ImageUrl))
                {
                    // wwwroot\images\product\test.jpg
                    var oldImagePath = Path.Combine(uploads, productVM.Product.ImageUrl);

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }

                //บันทึกรุปภาพใหม่
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                productVM.Product.ImageUrl = fileName + extension;
            }

            #endregion การจัดการูปภาพ

            var id = productVM.Product.Id;

            if (id != 0)
            {
                //update
                _productContext.Update(productVM.Product);
            }
            else
            {
                //create
                _productContext.Add(productVM.Product);
            }

            _productContext.SaveChanges();


            return RedirectToAction(nameof(Index));
        }


        public IActionResult Delete(int id)
        {
            var product = _productContext.Products.Find(id);

            if (product == null)
            {
                TempData["message"] = "ไม่พบข้อมูล";
                return RedirectToAction(nameof(Index));
            }

            if (!string.IsNullOrEmpty(product.ImageUrl))
            {
                // wwwroot\images\products\test.jpg
                var oldImagePath = _webHostEnvironment.WebRootPath + SD.ProductPath + "\\" + product.ImageUrl;

                if (System.IO.File.Exists(oldImagePath))
                {
                    System.IO.File.Delete(oldImagePath);
                }
            }


            _productContext.Remove(product);
            _productContext.SaveChanges();
            TempData["message"] = "ลบสำเร็จ";
            return RedirectToAction(nameof(Index));
        }
    }
}

ProductWeb/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using ProductWeb.Services;

namespace ProductWeb.Controllers
{
    public class RoleController : Controller
    {
        private readonly IRoleService _roleService;
        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _roleService.GetAll();
            return View(result);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleDto roleDto)
        {
            var result = await _roleService.Add(roleDto);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(string name)
        {
            var result = await _roleService.Find(name);

            var roleUpdate = new RoleUpdateDto { Name = result.Name };

            return View(roleUpdate);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleUpdateDto roleUpdateDto)
        {
            var result = await _roleService.Update(roleUpdateDto);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string name)
        {
            var result = await _roleService.Delete(name);

            return RedirectToAction(nameof(Index));
        }

    }
}

ProductWeb/Views/Shared/AlertView.cshtml
@if (TempData["message"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["message"]')
    </script>
}

ProductWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item"  asp-controller="Order" asp-action="Index">Order Management</a>
                                </div>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-cart-check-fill"></i>
                            </a>
                        </li>
                       
                    </ul>
                </div>

                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="AlertView" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProductWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/6.8.2/tinymce.min.js" integrity="sha512-6JR4bbn8rCKvrkdoTJd/VFyXAN4CE9XMtgykPWgKiHjou56YDJxWsi90hAeMTYxNwUnKSQu9JPc3SQUg+aGCHw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>